#!/usr/bin/env python3
"""music_gen.py — host-side generator: compiles the chiptune songs below into
src/music_data.h (const row tables in flash). Run from the repo root:

    python3 tools/music_gen.py

Notation (one song = 8 bars of 4/4, looping):
  lead: per bar, 8 tokens = 8th notes. "E5" note, "A#5" sharp, "-" hold, "." rest.
  bass: per bar a chord root ("C", "A#", or two roots "F/G" = half bar each) and one
        shared 8-token pattern: "1" root, "8" root an octave up, "-" hold, "." rest.
  drums: per bar, 16 tokens = 16th notes: k kick, s snare, h hat, . nothing.
Row = one 16th note. Row cell codes: 0 = hold, 1 = note off, >= 2 = MIDI note
(drums: 0 none, 1 kick, 2 snare, 3 hat).
"""
import os

NOTE = {"C": 0, "C#": 1, "D": 2, "D#": 3, "E": 4, "F": 5, "F#": 6, "G": 7,
        "G#": 8, "A": 9, "A#": 10, "B": 11}

def midi(tok):
    name, octv = tok[:-1], int(tok[-1])
    return 12 * (octv + 1) + NOTE[name]

SONGS = {
    # Menu / title: heroic, C major.
    "TITLE": dict(bpm=140, duty=2, lead=[
        "E5 G5 C6 - B5 C6 G5 -",
        "A5 - E5 A5 C6 - B5 A5",
        "F5 A5 C6 - D6 C6 A5 F5",
        "G5 - B5 - D6 - B5 G5",
        "E5 G5 C6 - E6 - D6 C6",
        "C6 - A5 - E5 - A5 B5",
        "C6 - A5 F5 D6 - B5 G5",
        "C6 - - - G5 E5 G5 -",
    ], roots=["C", "A", "F", "G", "C", "A", "F/G", "C"], bass="1 8 1 8 1 8 1 8",
       drums=["k...h...s...h..."] * 7 + ["k...h...s.s.s.s."]),
    # Explore map: relaxed but upbeat walking groove, G major.
    "EXPLORE": dict(bpm=118, duty=4, lead=[
        "B4 - D5 G5 - - F#5 E5",
        "D5 - B4 - E5 - G5 -",
        "E5 - G5 - C6 B5 A5 G5",
        "F#5 - - - A5 - - -",
        "G5 - B5 - D6 - B5 G5",
        "E5 - G5 - B5 - A5 G5",
        "A5 - G5 - E5 - C5 -",
        "D5 - F#5 - A5 - D5 -",
    ], roots=["G", "E", "C", "D", "G", "E", "C", "D"], bass="1 - - 1 8 - 1 -",
       drums=["k.......s.....k."] * 3 + ["k.......s...s.h."]
             + ["k...h...s...h.k."] * 3 + ["k...h...s.ss.sss"]),
    # Battles: tense and driving, A minor.
    "BATTLE": dict(bpm=160, duty=4, lead=[
        "A5 A5 C6 A5 E6 - D6 C6",
        "B5 C6 B5 A5 G5 - E5 -",
        "F5 A5 C6 F6 E6 - C6 A5",
        "G5 B5 D6 G6 F6 - D6 B5",
        "A5 - E6 - A6 - G6 E6",
        "F6 E6 D6 C6 B5 C6 D6 -",
        "C6 - A5 - F5 - A5 C6",
        "B5 - G#5 - E5 - G#5 B5",
    ], roots=["A", "A", "F", "G", "A", "A", "F", "E"], bass="1 1 8 1 1 1 8 1",
       drums=["k.hks.h.kkh.s.hh"] * 7 + ["k.hks.h.s.s.ssss"]),
    # Arcade: bright and bouncy, F major.
    "ARCADE": dict(bpm=150, duty=2, lead=[
        "A5 - C6 - F6 - E6 C6",
        "G5 - C6 - E6 - D6 C6",
        "D6 - A5 - F5 - A5 D6",
        "D6 - - A#5 F5 - A#5 D6",
        "C6 A5 C6 F6 A6 - G6 F6",
        "E6 - C6 - G5 - C6 E6",
        "F6 - D6 A#5 G6 - E6 C6",
        "F6 - - - C6 - A5 -",
    ], roots=["F", "C", "D", "A#", "F", "C", "A#/C", "F"], bass="1 - 8 1 - 1 8 -",
       drums=["k...h...s...h..."] * 3 + ["k...h...s...h.s."]
             + ["k.h.h.k.s.h.h.k."] * 3 + ["k.h.s.h.s.s.ssss"]),
}

def bass_root(pc):
    m = 48 + pc                      # octave 3 (C3 = 48): audible on a tiny speaker
    return m

def build(song):
    rows = []
    for bar in range(8):
        lead = song["lead"][bar].split()
        bass = song["bass"].split()
        drums = song["drums"][bar]
        roots = song["roots"][bar].split("/")
        assert len(lead) == 8 and len(bass) == 8 and len(drums) == 16, bar
        for r in range(16):
            e = r // 2
            first = (r % 2 == 0)
            lt = lead[e]
            if lt == "-" or not first: lc = 0
            elif lt == ".": lc = 1
            else: lc = midi(lt)
            root = NOTE[roots[0] if (len(roots) == 1 or e < 4) else roots[1]]
            bt = bass[e]
            if not first: bc = 0 if bt != "." else 0
            elif bt == "-": bc = 0
            elif bt == ".": bc = 1
            elif bt == "1": bc = bass_root(root)
            elif bt == "8": bc = bass_root(root) + 12
            else: raise ValueError(bt)
            # A half-bar root change re-strikes even if the pattern says hold.
            if len(roots) == 2 and e == 4 and first and bc == 0: bc = bass_root(root)
            dc = {".": 0, "k": 1, "s": 2, "h": 3}[drums[r]]
            rows.append((lc, bc, dc))
    return rows

def main():
    out = ["// music_data.h — GENERATED by tools/music_gen.py. Do not edit by hand.",
           "// Rows are 16th notes: {lead, bass, drum}. 0 = hold, 1 = off, >=2 = MIDI note;",
           "// drum 0 none, 1 kick, 2 snare, 3 hat.",
           "#pragma once", "#include <stdint.h>", ""]
    names = []
    for name, song in SONGS.items():
        rows = build(song)
        names.append((name, song, len(rows)))
        out.append(f"const uint8_t SONG_{name}[{len(rows)}][3] = {{")
        for i in range(0, len(rows), 8):
            out.append("  " + " ".join("{%d,%d,%d}," % r for r in rows[i:i + 8]))
        out.append("};")
        out.append("")
    out.append("struct SongDef { const uint8_t (*rows)[3]; uint16_t count; uint16_t bpm; uint8_t duty; };")
    out.append("// duty: lead square duty = 1/duty (2 = 50%, 4 = 25%).")
    out.append("const SongDef SONGS[] = {")
    for name, song, n in names:
        out.append(f"  {{ SONG_{name}, {n}, {song['bpm']}, {song['duty']} }},   // {name}")
    out.append("};")
    path = os.path.join(os.path.dirname(__file__), "..", "src", "music_data.h")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", os.path.normpath(path), [(n, c) for n, _, c in names])

if __name__ == "__main__":
    main()
