// audio.h — sound on the onboard I2S amp: a tiny square/noise synth in its own task.
// SFX (2 voices) play over a looping chiptune track (M1). Game code calls play(Sfx)
// and music(Track); nothing else touches audio.
#pragma once
#include <stdint.h>

namespace audio {

enum class Sfx : uint8_t {
  Boot,      // rising 3-note chime (bring-up check)
  Tap,       // menu button
  Jump, Duck, Coin, Orb,
  Hit,       // stumble / crash
  Win, Lose,
  Count
};

bool init();          // start I2S + synth task; returns false if the driver failed
void play(Sfx s);     // fire-and-forget; a new SFX on a busy voice replaces it
bool ok();            // driver started

// Music: order matches SONGS in music_data.h (generated by tools/music_gen.py).
enum class Track : int8_t { None = -1, Title = 0, Explore = 1, Battle = 2, Arcade = 3 };
void music(Track t);  // switch track (restarts from the top); same track = no-op

// Volume: levels 0..AUDIO_LEVELS (0 = off). Mute silences both without losing levels.
void    setLevels(uint8_t musicLevel, uint8_t sfxLevel);
uint8_t musicLevel();
uint8_t sfxLevel();
void    setMuted(bool m);
bool    muted();

}
