// sprite.h — palette-indexed sprite blitter (A1 art). Writes the SRAM band buffer
// directly (no pushImage, no LovyanGFX per-pixel calls): nearest-neighbour scaling to
// any size, optional horizontal flip, index 0 = transparent. Art lives in flash
// (src/art_data.h, generated by tools/art_gen.py); the shared palette is converted
// to band-buffer byte order once at init.
#pragma once
#include <LovyanGFX.hpp>
#include <stdint.h>
#include "art_data.h"

namespace sprite {

bool init();   // after renderer::init (needs renderer::raw)

// Draw `s` into the band, scaled to dw x dh screen px with its top-left at (x, y)
// in screen coordinates. Clipped to the band and the screen.
void draw(lgfx::LGFX_Sprite& band, int32_t bandY, const ArtSprite& s, int32_t x, int32_t y,
          int32_t dw, int32_t dh, bool flipX = false);

// Same, positioned by bottom-centre (cx, bottomY) at a uniform integer-ish scale.
inline void drawBottom(lgfx::LGFX_Sprite& band, int32_t bandY, const ArtSprite& s, int32_t cx,
                       int32_t bottomY, float scale, bool flipX = false) {
  const int32_t dw = (int32_t)(s.w * scale + 0.5f), dh = (int32_t)(s.h * scale + 0.5f);
  draw(band, bandY, s, cx - dw / 2, bottomY - dh, dw, dh, flipX);
}

}
